//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 10:40:54 PM UTC 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "servletNameOrUrlPattern",
    "cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField"
})
@XmlRootElement(name = "cache-mapping")
public class CacheMapping
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElements({
        @XmlElement(name = "servlet-name", required = true, type = ServletName.class),
        @XmlElement(name = "url-pattern", required = true, type = UrlPattern.class)
    })
    protected List<Serializable> servletNameOrUrlPattern;
    @XmlElements({
        @XmlElement(name = "cache-helper-ref", type = CacheHelperRef.class),
        @XmlElement(name = "dispatcher", type = Dispatcher.class),
        @XmlElement(name = "timeout", type = Timeout.class),
        @XmlElement(name = "refresh-field", type = RefreshField.class),
        @XmlElement(name = "http-method", type = HttpMethod.class),
        @XmlElement(name = "key-field", type = KeyField.class),
        @XmlElement(name = "constraint-field", type = ConstraintField.class)
    })
    protected List<Serializable> cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField;

    /**
     * Gets the value of the servletNameOrUrlPattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the servletNameOrUrlPattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServletNameOrUrlPattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServletName }
     * {@link UrlPattern }
     * 
     * 
     */
    public List<Serializable> getServletNameOrUrlPattern() {
        if (servletNameOrUrlPattern == null) {
            servletNameOrUrlPattern = new ArrayList<Serializable>();
        }
        return this.servletNameOrUrlPattern;
    }

    /**
     * Gets the value of the cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CacheHelperRef }
     * {@link Dispatcher }
     * {@link Timeout }
     * {@link RefreshField }
     * {@link HttpMethod }
     * {@link KeyField }
     * {@link ConstraintField }
     * 
     * 
     */
    public List<Serializable> getCacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField() {
        if (cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField == null) {
            cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField = new ArrayList<Serializable>();
        }
        return this.cacheHelperRefOrDispatcherOrTimeoutOrRefreshFieldOrHttpMethodOrKeyFieldOrConstraintField;
    }

}
