//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 10:40:54 PM UTC 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localeCharsetMap",
    "parameterEncoding"
})
@XmlRootElement(name = "locale-charset-info")
public class LocaleCharsetInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "default-locale")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultLocale;
    @XmlElement(name = "locale-charset-map", required = true)
    protected List<LocaleCharsetMap> localeCharsetMap;
    @XmlElement(name = "parameter-encoding")
    protected ParameterEncoding parameterEncoding;

    /**
     * Gets the value of the defaultLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLocale() {
        return defaultLocale;
    }

    /**
     * Sets the value of the defaultLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLocale(String value) {
        this.defaultLocale = value;
    }

    /**
     * Gets the value of the localeCharsetMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localeCharsetMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocaleCharsetMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocaleCharsetMap }
     * 
     * 
     */
    public List<LocaleCharsetMap> getLocaleCharsetMap() {
        if (localeCharsetMap == null) {
            localeCharsetMap = new ArrayList<LocaleCharsetMap>();
        }
        return this.localeCharsetMap;
    }

    /**
     * Gets the value of the parameterEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterEncoding }
     *     
     */
    public ParameterEncoding getParameterEncoding() {
        return parameterEncoding;
    }

    /**
     * Sets the value of the parameterEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterEncoding }
     *     
     */
    public void setParameterEncoding(ParameterEncoding value) {
        this.parameterEncoding = value;
    }

}
