//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 10:40:54 PM UTC 
//


package com.sun.ts.lib.implementation.sun.javaee.runtime.web;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parameter-encoding")
public class ParameterEncoding
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "form-hint-field")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String formHintField;
    @XmlAttribute(name = "default-charset")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String defaultCharset;

    /**
     * Gets the value of the formHintField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormHintField() {
        return formHintField;
    }

    /**
     * Sets the value of the formHintField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormHintField(String value) {
        this.formHintField = value;
    }

    /**
     * Gets the value of the defaultCharset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCharset() {
        return defaultCharset;
    }

    /**
     * Sets the value of the defaultCharset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCharset(String value) {
        this.defaultCharset = value;
    }

}
